controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    parallel_gripper_action_controller:
      type: parallel_gripper_action_controller/GripperActionController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

parallel_gripper_action_controller:
  ros__parameters:
    joint: grip2_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
