<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm_model">

  <!-- *********************** PROPERTIES *********************** -->
  <xacro:property name="base_width" value="0.3"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="arm_width" value="0.1"/>
  <xacro:property name="arm_length" value="0.5"/>

  <!-- *********************** MATERIALS *********************** -->
  <!-- Materials are defined once at the top level, like in the tutorial -->
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>
  <material name="silver">
    <color rgba="0.75 0.75 0.75 1.0"/>
  </material>

  <!-- *********************** LINKS *********************** -->

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_width} ${base_width} ${base_height}"/>
      </geometry>
      <!-- Reference the material by name -->
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_width} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.01875" ixy="0.0" ixz="0.0" iyy="0.01875" iyz="0.0" izz="0.03"/>
    </inertial>
  </link>

  <!-- Virtual Link for 2-DOF Joint -->
  <link name="base_arm1_virtual_link">
    <inertial>
      <mass value="1e-5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <!-- First Arm Link -->
  <link name="arm1_link">
    <visual>
      <origin xyz="0 0 ${arm_length/2}"/>
      <geometry>
        <box size="${arm_width} ${arm_width} ${arm_length}"/>
      </geometry>
      <!-- Reference the material by name -->
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${arm_length/2}"/>
      <geometry>
        <box size="${arm_width} ${arm_width} ${arm_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${arm_length/2}"/>
      <mass value="1.0"/>
      <inertia ixx="0.0217" ixy="0.0" ixz="0.0" iyy="0.0217" iyz="0.0" izz="0.0017"/>
    </inertial>
  </link>

  <!-- Second Arm Link -->
  <link name="arm2_link">
    <visual>
      <origin xyz="0 0 ${arm_length/2}"/>
      <geometry>
        <box size="${arm_width} ${arm_width} ${arm_length}"/>
      </geometry>
      <!-- Reference the material by name -->
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${arm_length/2}"/>
      <geometry>
        <box size="${arm_width} ${arm_width} ${arm_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${arm_length/2}"/>
      <mass value="1.0"/>
      <inertia ixx="0.0217" ixy="0.0" ixz="0.0" iyy="0.0217" iyz="0.0" izz="0.0017"/>
    </inertial>
  </link>

  <!-- *********************** JOINTS *********************** -->

  <joint name="base_to_arm1_virtual" type="continuous">
    <parent link="base_link"/>
    <child link="base_arm1_virtual_link"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${base_height/2}"/>
  </joint>

  <joint name="arm1_virtual_to_arm1" type="continuous">
    <parent link="base_arm1_virtual_link"/>
    <child link="arm1_link"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0 0 0"/>
  </joint>

  <joint name="arm1_to_arm2" type="continuous">
    <parent link="arm1_link"/>
    <child link="arm2_link"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0 0 ${arm_length}"/>
  </joint>
</robot>
