# All parameters for the controller manager must be nested under its name
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    # The types of the controllers are defined here
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


# All parameters for the joint_trajectory_controller must be nested under its name
joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
